services:
  scrapper:
    container_name: aladdin-scrapper
    build:
      context: ./apps/scrapper
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-8080}
        - USER_ID=${USER_ID:? USER_ID is Required}
        - AMAZON_PLATFORM_ID=${AMAZON_PLATFORM_ID:? AMAZON_PLATFORM_ID is Required}
        - FLIPKART_PLATFORM_ID=${FLIPKART_PLATFORM_ID:? FLIPKART_PLATFORM_ID is Required}
        - REDIS_HOST=${REDIS_HOST:? REDIS_HOST is Required}
        - REDIS_PORT=${REDIS_PORT:? REDIS_PORT is Required}
        - REDIS_PASSWORD=${REDIS_PASSWORD:? REDIS_PASSWORD is Required}
        - SUPABASE_URL=${SUPABASE_URL:? SUPABASE_URL is Required}
        - SUPABASE_KEY=${SUPABASE_KEY:? SUPABASE_KEY is Required}
        - SCREENSHOT_SERVICE_URL=${SCREENSHOT_SERVICE_URL:? SCREENSHOT_SERVICE_URL is Required}
    ports:
      - "8080:8080"

  screenshot-service:
    container_name: aladdin-screenshot
    build:
      context: ./apps/screenshot
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3000}
        - SUPABASE_URL=${SUPABASE_URL:? SUPABASE_URL is Required}
        - SUPABASE_KEY=${SUPABASE_KEY:? SUPABASE_KEY is Required}
    ports:
      - "3000:3000"

volumes:
  screenshot-data:
  scrapper-data:
